### ISSUE TITLE
compilation error, what i am doing wrong?

### ISSUE THREAD

**Issue by afmecofe** [ronisbr/ControlToolbox.jl#2]
using ControlToolbox
[ Info: Precompiling ControlToolbox [059e8e86-8a00-5752-9d3d-adbce60f63dd]
ERROR: LoadError: syntax: extra token "StateSpace" after end of expression
Stacktrace:
 [1] include at ./boot.jl:326 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:328 [inlined]
 [6] eval(::Expr) at ./client.jl:404
 [7] top-level scope at ./none:3
in expression starting at /home/.julia/dev/ControlToolbox/src/ControlToolbox.jl:26
ERROR: Failed to precompile ControlToolbox [059e8e86-8a00-5752-9d3d-adbce60f63dd] to /home/.julia/compiled/v1.1/ControlToolbox/K9DGS.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853

**Comment by ronisbr** [comment]
Hi @CooviM 

This package is not supported anymore and does not work with Julia 1.0. For a much better alternative, please use this one: https://github.com/JuliaControl/ControlSystems.jl

**Comment by afmecofe** [comment]
Thanks for the quick response. 
Best
Coovi
